//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tema2MTP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefoane
    {
        public int ID_Telefon { get; set; }
        public string Model { get; set; }
        public System.DateTime An_Fabricatie { get; set; }
        public string Specificatii { get; set; }
        public int Pret { get; set; }
        public int Stoc { get; set; }
    }
}
